name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Login to DockerHub
    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t cicd-pipeline .

    # Push the Docker image to DockerHub
    - name: Push to DockerHub
      run: docker push vinay9301/cicd-pipeline:latest
